Dockerfile, Makefile, README.md
This PR is for adding a feature to build a binary within a docker container. It is useful if the customer don't want to setup Go environment for building.
Note: If you use a remote Docker Machine, this won't work since the local volume is not mounted to the container directly.
=> Add Dockerfile and make docker target

ecr-login/api/client_test.go, ecr-login/cache/credentials.go, ecr-login/cache/credentials_test.go, ecr-login/cache/file_test.go
Fixes #7
This carries #8 from @f-barth and attempts to make the logic more readable.
r? @sentientmonkey
=> Make expiration logic more readable

Makefile, scripts/build_binary.sh
https://github.com/awslabs/amazon-ecr-credential-helper/issues/12
Cross-architecture compilation with `make docker TARGET_GOARCH=arm`.
```
$ make
Built ecr-login
$ file bin/local/docker-credential-ecr-login 
bin/local/docker-credential-ecr-login: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), statically linked, stripped
$ make docker TARGET_GOARCH=arm
Built ecr-login
$ file bin/local/docker-credential-ecr-login 
bin/local/docker-credential-ecr-login: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```
=> TARGET_GOARCH for cross-architecture compilation

scripts/gogenerate
This excludes vendored go:generate lines from being executed by `make gogenerate`.
=> gogenerate: Exclude vendored go:generate lines

ecr-login/api/client.go, ecr-login/api/client_test.go, ecr-login/api/factory.go, ecr-login/ecr.go, ecr-login/ecr_test.go, ecr-login/mocks/ecr_mocks.go, scripts/generate/mockgen.sh
* GetCredential returns proxyEndpoint
* NewClient uses AWSConfig
=> Make this reusable for amazon-ecs-cli

ecr-login/Godeps/Godeps.json, ecr-login/api/client.go, ecr-login/api/client_test.go, ecr-login/api/factory.go, ecr-login/cache/build.go, ecr-login/cache/build_test.go, ecr-login/cache/credentials.go, ecr-login/cache/file.go, ecr-login/cache/file_test.go, ecr-login/cache/mocks/cache_mocks.go, ecr-login/cache/null.go, ecr-login/cache/null_test.go, ecr-login/ecr.go, ecr-login/ecr_test.go, ecr-login/mocks/ecr_mocks.go, ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go, ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/error.go, ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/helper.go
Beginning on implementation for the List API to fix #23. This vends the latest docker-credential-helper and fixes the build by providing a notImplemented interface for List.
From looking at the List API implementation, this appears to return all service urls and usernames. We should be able to provide similar functionality by walking the cache file and returning all of the repositories and usernames within the auth tokens. Repositories not already cached will not be returned. Anyone using the null cache will never get any values returned as well. We should also be able to implement Erase, but Add still doesn't really make sense for our use cases.
The major area we'll have to refactor here is that the ClientFactory today is created regionally, and the cache really global. I think the right …
=> Implement helper list

ecr-login/api/client.go, ecr-login/api/client_test.go, ecr-login/ecr.go, ecr-login/ecr_test.go, ecr-login/mocks/ecr_mocks.go
This is based upon https://github.com/awslabs/amazon-ecr-credential-helper/pull/26. The purpose is to make `docker build --pull` can still work even cache doesn't exist, hence fully address https://github.com/awslabs/amazon-ecr-credential-helper/issues/23. Basically, in the ListCredentials() function I invoked getAuthorizationToken for default registry if there's no credential cache. It only requires the user has set AWS_REGION environment variable.
Also refactored a bit the code:
- Client.GetCredentials() just needs one serverURL parameter. It can parse registry and region. 
- Client.GetCredentials() can auto remove the `https://` prefix from serverURL.
- Client.ListCredentials() and ECR.List() can return proxyEndpointUrl which has `https://` prefix.
- Extracted common logics of …
=> Get default registry's credential when List if cache doesn't exist

README.md
This section can be removed once docker-compose supports `credHelpers` again.
=> Explain credHelpers doesn't work with docker-compose

buildspec.yml, scripts/hack/symlink-gopath-codebuild.sh
I'd like to rebase this on top of https://github.com/awslabs/amazon-ecr-credential-helper/pull/60 so I can use `make all-variants` instead of `make`, but this works as-is with the `golang:1.9` image as the build environment.
```
$ aws codebuild batch-get-projects --names amazon-ecr-credential-helper
{
"projectsNotFound": [], 
"projects": [
{
"name": "amazon-ecr-credential-helper", 
"serviceRole": "--REDACTED--", 
"tags": [], 
"artifacts": {
"namespaceType": "BUILD_ID", 
"packaging": "NONE", 
"type": "S3", 
"location": "--REDACTED--", 
"name": "amazon-ecr-credential-helper"
}, 
"lastModified": 1503641247.019, 
"timeoutInMinutes": 60, 
"created": 1503634196.49, 
"environment": {
"computeType": "BUILD_GENERAL1_SMALL", 
"image": "golang:1.9", 
"type": "LINUX_CONTAINER", …
```
=> First buildspec

Makefile
To account for spaces in the path
=> Quote host volume path in 'make docker' task

.travis.yml, ecr-login/api/client.go
* Added 1.10 to the list of Go versions that are tested
* Ensured that the cross-compilation targets defined in the Makefile are tested
* Ran `gofmt -s` on `api/client.go`
=> Test Go 1.10, cross-compilation targets

Makefile
If we just clone this repository and do `make docker` the command won't work.
We must ensure bin directory exists before mounting docker volume for build.
*Issue #* #62 
create bin directory before running docker that mounts it as a volume.
=> Create bin directory for docker output

THIRD-PARTY-LICENSES
THIRD-PARTY-LICENSES file shows attribution data for the vendored dependencies.
=> Add attribution document

.gitignore, Makefile, Makefile.amazonlinux, amazon-ecr-credential-helper.spec, docs/packaging-amazon-linux.md, packaging/amazon-linux/Dockerfile.rpm
Initial packaging of an RPM for Amazon Linux 2.
Tested with `make docker-rpm`, which produced `amazon-ecr-credential-helper-0.1.0-1.amzn2.x86_64.rpm` and was install-able into an `amazonlinux:2` container.
Still TODO:
/cc @jahkeup 
=> Initial Amazon Linux packaging

ecr-login/api/factory.go, ecr-login/ecr.go, ecr-login/mocks/ecr_mocks.go
Setting ResolveUnknownService flag to be true on the Endpoint Resolver
allows the resolver to fall back to its default endpoint construction
pattern if it cannot find an explicit reference to a service endpoint.
This allows proper handling of cases where services may not
have released an updated endpoints definition.
=> Correctly handle UnknownServiceError

README.md, docs/packaging.md
Additional community-maintained packages are listed at https://repology.org/metapackage/amazon-ecr-credential-helper/versions; adding them here.
I don't have installation instructions in the README for Nix/NixOS yet; I'd welcome suggestions for that.
=> docs: add community-maintained packages

docs/packaging-amazon-linux.md
Fix markdown link in the packaging docs.
=> docs: Fix markdown link syntax

README.md
*Issue #, if available:* 101
Added note about golang PATH definitions being required prior to installing from source. Otherwise the install will fail silently.
=> Extra notes for installing from source

ecr-login/config/log.go
https://github.com/awslabs/amazon-ecr-credential-helper/issues/162
Ensure the log directory is created so that logs are put in the log file instead of standard out.
cc @jbergknoff-rival, @sipsma
=> log: create log directory if missing

.codebuild/buildspec.yml, .codebuild/source-archive.yml, scripts/hack/codepipeline-git-commit.sh, scripts/hack/codepipeline-source-archive.sh, scripts/hack/version-changelog.sh
This commit sets up buildspecs for two different AWS CodeBuild builds,
intended to be run from AWS CodePipeline.  The main buildspec builds all
variants of the binary, and can also be run directly in AWS CodeBuild
with no changes.  The second buildspec produces correct source archives
that include commit information but not a complete git repository, as
well as metadata files like a version-specific section of the
CHANGELOG.md.
cc @sipsma
=> .codebuild: scripts for release pipeline

Makefile
*Issue #, if available:* #184 
* Made `GITCOMMIT_SHA` a dependency of the `docker` Make target.
=> Fix `make docker` when repo is a submodule

debian/copyright
This package is now built using an upstream tarball that does not
contain the excluded files.  Removing the Files-Excluded marker as they
are not included in that tarball.
=> debian: remove Files-Excluded from d/copyright

README.md, docs/docker-credential-ecr-login.1, ecr-login/api/factory.go, ecr-login/api/factory_test.go
Fixes #198 
The AWS SDK for Go ignores the shared config file `~/.aws/config` by
default, which is the inherited behavior of
amazon-ecr-credential-helper. This commit changes the default behavior
to have `~/.aws/config` enabled.
The shared config file usage can be controlled through the environment
variable `AWS_SDK_LOAD_CONFIG`. To disable this behavior, set
`AWS_SDK_LOAD_CONFIG=false`.
=> api: enable shared config by default

CHANGELOG.md
Include https://github.com/awslabs/amazon-ecr-credential-helper/pull/201 in the changelog
=> changelog: update for shared config enhancement

debian/changelog, debian/control, debian/upstream/metadata, debian/watch
Fix some issues reported by lintian
* Set upstream metadata fields: Bug-Database, Bug-Submit, Repository, Repository-Browse. ([upstream-metadata-missing-bug-tracking](https://lintian.debian.org/tags/upstream-metadata-missing-bug-tracking.html), [upstream-metadata-missing-repository](https://lintian.debian.org/tags/upstream-metadata-missing-repository.html))
* Add debian/watch file, using github. ([debian-watch-file-is-missing](https://lintian.debian.org/tags/debian-watch-file-is-missing.html))
* Use canonical URL in Vcs-Git. ([vcs-field-not-canonical](https://lintian.debian.org/tags/vcs-field-not-canonical.html))
* Update standards version to 4.5.0, no changes needed. ([out-of-date-standards-version](https://lintian.debian.org/tags/out-of-date-standards-version.html))
This merge proposal …
=> Fix some issues reported by lintian

debian/amazon-ecr-credential-helper.docs, debian/changelog
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962304
> As discussed outside the BTS, there is a man page, but its name corresponds with a binary that a user would never directly execute (it is run automatically by docker).  So it's not really clear which man page to consult to learn the proper configuration.  So, it would still be helpful to have README.md in place.
>
> Alternatively, symlinking the manual page to something more easily discoverable could help.  Since there's no binary named "amazon-ecr-credential-helper", it should not go in section 1.  Section 7 seems most appropriate.  But then the man page's header would be
wrong. (it'd still reference section 1)
>
> The attached patch will install README.md to the appropriate …
=> debian: Install README.md to /usr/share/doc

debian/changelog, debian/control, debian/watch
Per https://www.debian.org/doc/debian-policy/ch-controlfields.html#version-control-system-vcs-fields, `Vcs-*` are intended to point to the source of the packaging, which in this case is a little conflated because it's part of the upstream repo, but thankfully there is a provision for `Vcs-Git` to supply a branch name. :partying_face: 
(This should make it easier for folks to find the `debian/` directory in the future. :smile:)
Also, I've updated the Janitor's `debian/watch` file to properly download the `release-novendor.tar.gz` files from https://github.com/awslabs/amazon-ecr-credential-helper/releases (so that `uscan` does-the-right-thing).
As a final treat, I've added `golang-github-stretchr-testify-dev` to `Build-Depends`, which fixes https://bugs.debian.org/973063. :metal:
By …
=> debian: Update "Vcs-*" tags, fix d/watch, add testify to B-D

README.md
I ran into an issue with my coworkers today while onboarding our ECR environment where it wasn't obvious that the region needed to be set in their docker config.
We ended up with the failure mode that they had a literal `region` in their config instead of something like `us-east-1`.
I've wrapped the two things that need to be replaced with `<>`.
=> README: Obvious string replacement for ECR URI

.github/workflows/build.yaml
This change removes Go 1.11 from GitHub Actions to unblock #253.
Go 1.11 doesn't work on macOS 10.05 after upgrading golang.org/x/sys.
While we could downgrade golang.org/x/sys, Go 1.11 is no longer
supported by the Go team and most OSes tend to have newer Go packages.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
=> Drop Go 1.11 support

ecr-login/version/version.go
The default version is used when this repository is built from source using a default `go build` command.  The primary development branch has been renamed from "master" to "main", but using the branch name as the version isn't super clear.  The new "development" default version makes it clear that the binary was built from source.
=> version: rename default version

.github/workflows/build.yaml
Fixes the GitHub Actions workflow to make sure it runs on the new `main` branch.
=> .github: switch branch from master to main

Makefile
The `Makefile` will reach into the `.git` directory without checking, causing an error to print from the `find` command run here. Instead, the shell can check for the directory first, and then list if present.
=> build: check for git dir when listing

ecr-login/go.mod, ecr-login/go.sum
I want to get the fix for aws/aws-sdk-go#3763 which is in 1.38.42 so I
can use an aws profile that has both sso and `credential_process`
configuration in a single profile
=> Update aws-sdk-go to 1.38.44

.github/workflows/build.yaml
Go 1.12 is no longer supported by the Go team and AWS SDK v2
(technically speaking github.com/aws/smithy-go) doesn work with
the version.
Go 1.16 is the latest version, released in 2021-02-16.
https://blog.golang.org/go1.16
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
=> Update Go versions on GitHub Actions

ecr-login/cli/docker-credential-ecr-login/main.go, ecr-login/ecr.go, ecr-login/ecr_test.go
Signed-off-by: Jason Hall <jasonhall@redhat.com>
Though this code is typically consumed as a CLI cred helper configured for use with the `docker` CLI, we've also found it to be really useful as a Go client for generating ECR credentials from the environment.
[`go-containerregistry`](https://github.com/google/go-containerregistry), which is used by [Tekton](https://tekton.dev), [Knative](https://knative.dev), [`ko`](https://github.com/google/ko), [`cosign`](https://github.com/sigstore/cosign), [Kaniko](https://kaniko.dev), [Buildpacks](https://buildpacks.io) and more, provides an adapter between its auth-providing [`authn.Keychain`](https://godoc.org/github.com/google/go-containerregistry/pkg/authn#Keychain) interface, and Docker's `credential.Helper` interface, …
=> Allow callers to set log output

scripts/build_binary.sh
Produce reproducible builds #186 
Adds `-trimpath` to remove local paths from executable and sets build id to empty string using `-ldflags=-buildid=`. Both flags are required for reproducible builds.
=> Add go build flags to ensure reproducible builds

README.md
This changes the README's `go get` to `go install` as `go get` is deprecated and now returns
```
go get: installing executables with 'go get' in module mode is deprecated.
```
https://golang.org/doc/go-get-install-deprecation
=> Update go command to account for deprecation of go get

.github/workflows/build.yaml, Dockerfile, Makefile, README.md
Go 1.13 is no longer supported by the Go team and AWS SDK for Go requires
Go 1.15.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
=> Recommend Go 1.15 or later

Makefile.amazonlinux, scripts/build_binary.sh
Pass --buildid as ldflag otherwise rpmbuild fails. Golang compiler adds its own build-id into the binary, named .note.go.build-id. However, rpmbuild wants Fedora compatible build-id, in the format note.gnu.build-id.
Signed-off-by: Swagat Bora <sbora@amazon.com>
*Issue #, if available:* https://t.corp.amazon.com/P68468819
Saw that the `main` branch is already passing the `buildid` ldflag, which was missing in the `amazonlinux` branch. This was causing rpmbuild to fail. There was another issue which I believe is caused due to stripping on symbol table while the binaries were built. This was fixed by passing -D 'debug_package %{nil}` during rpmbuild
```
RPM build errors:
Empty %files file /home/ec2-user/amazon-ecr-credential-helper/BUILD/amazon-ecr-credential-helper- …
```
=> Fix Missing build-id issue during rpm build

Makefile.amazonlinux, amazon-ecr-credential-helper.spec
Signed-off-by: Swagat Bora <sbora@amazon.com>
*Issue #, if available:* 
*Description of changes:* Al2022 rpmbuild is seeing failure whille trying to build debuginfo package. Earlier, we disabled debug build in our Makefile.amazonlinux in `make rpm` target. However, Koji builds calls rpmbuild directly and tries to build debug package. 
As a result, now we have updated the .spec file itself to disable debug build if building for AL2022. 
=> Disable debug package rpm build for AL2022

README.md
Updated build badge to point to GitHub actions build instead of TravisCI. Updated Linux repology badges for Debian and Ubuntu packages.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
Resolves #380
Resolves #414
Updates build badge and Linux repository badges in readme.
=> Fix readme badges.

README.md
resolves #353
Added tiny example of `~/.docker/config.json` showing Amazon ECR Docker Helper config alongside other non-ECR docker registry auth tokens.
=> docs(README): multiple registry config example

README.md
Add Amazon Linux 2023 to the Install section, as `amazon-ecr-credential-helper` is available in the AL2023 repositories.
=> Add Amazon Linux 2023 to README

README.md
Replace `#Configuration` with `#configuration` to fix internal link to Configuration section.
=> Fix internal link to "Configuration section"

.github/workflows/build.yaml, Dockerfile
Fixes #579 
outdated version of Go in Dockerfile resulted in build failures. Add step in CI to build in Dockerfile for future regressions.
=> fix: upgrade Dockerfile to go 1.19

.github/workflows/build.yaml
N/A
Go 1.21 is released. This PR adds support to the CI.
=> Add Go 1.21 to CI

ecr-login/cli/docker-credential-ecr-login/main.go
Fixes #432: Release version inconsistent with docker-credential-ecr-login version 
During build, override the name/package/version/revision fields defined in [docker-credential-helpers/blob/master/credentials/version.go](https://github.com/docker/docker-credential-helpers/blob/master/credentials/version.go)
=> Fixes #432, override docker-credential-helpers version fields

ecr-login/api/client.go, ecr-login/api/client_test.go
433
Update the ecrPattern to include c2s environments
=> Update ECR pattern to include C2S environments

.github/workflows/build.yaml
Contributors can accidentally submit git secrets to version control.
This change enables git secrets in CI to prevent sensitive information being contributed to version control.
=> Enable git secrets scanning in CI

Makefile
Add support for win/arm64 target
---
=> ci: support win/arm64 target

.github/workflows/build.yaml
Closes #790 
There is a lack of coverage for the Windows platform in CI.
This change adds Windows unit testing to GitHub Actions CI matrix.
=> Add windows to ci

README.md
Clarify the support model for the Dockerfile included in the Amazon ECR credential helper repository.
This change adds a disclaimer regarding the support of the Dockerfile provided for cross compiling the Amazon ECR credential helper binaries and locally building from source using Docker.
=> Add disclaimer for container image support to readme

Makefile, scripts/container_init.sh
Fixes the following error when running `make build-in-docker` for ISSUE: https://github.com/awslabs/amazon-ecr-credential-helper/issues/800
```
git rev-parse --short=7 HEAD > GITCOMMIT_SHA
fatal: detected dubious ownership in repository at '/go/src/github.com/awslabs/amazon-ecr-credential-helper'
To add an exception for this directory, call:
git config --global --add safe.directory /go/src/github.com/awslabs/amazon-ecr-credential-helper
make: *** [Makefile:95: GITCOMMIT_SHA] Error 128
```
- Adds `/go/src/github.com/awslabs/amazon-ecr-credential-helper` to git as a safe directory. 
=> Add awslabs to git safe dir

.github/dependabot.yml
The Amazon ECR credential helper depends on multiple modules from the AWS SDK Go v2 project and is automated pull requests are frequently made to keep the packages up-to-date. The problem is some of the modules depend on each other and must be applied in a specific order to truly be considered atomic updates. This is difficult to maintain and an alternative consideration is to group all the AWS SDK updates into a single commit to simplify maintenance of the updates.
This change adds dependabot configuration to group updates to aws/aws-sdk-go-v2 dependencies. The v2 of the Go SDK distributes multiple modules required by the Amazon ECR credential helper. This will reduce the effort required to keep the dependencies up-to-date.
By submitting …
=> Group updates to aws/aws-sdk-go-v2 dependencies

README.md, ecr-login/ecr.go, ecr-login/ecr_test.go
Issue #, if available: https://github.com/awslabs/amazon-ecr-credential-helper/issues/102 & https://github.com/awslabs/amazon-ecr-credential-helper/issues/154
Description of changes:
(Revive of https://github.com/awslabs/amazon-ecr-credential-helper/pull/315)
Currently, both the Add and Delete operations in this helper return a not implemented error. This can lead to issues where docker login and docker logout stop working for the user while displaying a confusing not implemented error.
Following the suggestion in https://github.com/awslabs/amazon-ecr-credential-helper/issues/154#issuecomment-475000495, this PR adds an environment variable (AWS_ECR_IGNORE_CREDS_STORAGE) to optionally ignore these requests and return no error. When AWS_ECR_IGNORE_CREDS_STORAGE=true, instead of returning a …
=> Implement both the Add and Delete operations as no-ops

ecr-login/api/client.go, ecr-login/api/client_test.go
N/A
This change expands the ECR pattern to allow for the new ISO-E and ISO-F partitions.
=> Add support for AWS ISO-E and ISO-F partitions

.github/workflows/build.yaml, ecr-login/go.mod
N/A
This change adds Go 1.22 to CI
=> Add Go 1.22 to CI

CHANGELOG.md
The releases for v0.7.1 and v0.8.0 were not fully merged into main. In the case of v0.7.1, the only change was the changelog, so it wasn't merged at all. In the case of v0.8.0, the change was merged either by rebase or squash so the commit ID changed which means the tag for v0.8.0 doesn't point to a commit in main.
This fully merges these branches so that main is fully in sync and going forward we can push to staging from main for releases. 
=> Merge release/v0.7 and staging into main

docs/packaging.md
One of the [CI action runs](https://github.com/awslabs/amazon-ecr-credential-helper/actions/runs/12417094152/job/34834914714?pr=909) is failing due to a invalid link in docs/packaging.md 
Update the doc to point to the new location in nixOS 
=> fix: invalid url link in packaging.md

.github/workflows/build.yaml, ecr-login/go.mod
*Issue #, if available:* #925
- Drops support for golang 1.21 since it is now unmaintained
=> build(deps): drop golang 1.21

ecr-login/config/log.go
File permissions for ecr-login.log
Changed permissions to 0644
=> fix: file permissions for ecr-login

README.md
GitHub has a handy feature where readers can click a copy button to copy the context of a code block. In this case, when you copy these blocks - the dollar sign is included. 
We can do better. Having the language declared at the top of the code block should suffice.
- removes dollar signs from bash/shell code blocks in the root Readme.
=> chore: remove dollar signs from scripts in readme
