- .travis.yml
- Makefile
- README.md
- scripts/hack/symlink-gopath-travisci
> Enable Travis

- README.md
> readme: fix typo in build status badge

- ecr-login/api/factory.go
- ecr-login/cache/build.go
- ecr-login/cache/build_test.go
- ecr-login/mocks/ecr_mocks.go
```
$ make build
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local
Built ecr-login
```
```
$ make gogenerate
```
```
$ make test
PASS
```
> Create a new constructor to take in cache dir

- README.md
'docker push' command was specified twice
> updated usage section

- scripts/build_binary.sh
Carries https://github.com/awslabs/amazon-ecr-credential-helper/pull/57
> fix build_binary.sh

- Makefile
- scripts/build_variant.sh
@rpnguyen I can't seem to request a review from you here, but can you take a look too?
@nmeyerhans If you have any suggestions on cleaning up the Makefile I'm all ears. :smile:
> makefile: targets for different variants

- README.md
According to [the linked pull request](https://github.com/docker/compose/issues/4948), Docker Compose now supports this functionality as of version 1.15.
> Now works with Docker Compose

- ecr-login/Gopkg.lock
- ecr-login/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- ecr-login/vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
- ecr-login/vendor/github.com/aws/aws-sdk-go/aws/session/session.go
- ecr-login/vendor/github.com/aws/aws-sdk-go/aws/version.go
- ecr-login/vendor/github.com/aws/aws-sdk-go/service/ecr/api.go
- ecr-login/vendor/github.com/aws/aws-sdk-go/service/sts/api.go
Fixes https://github.com/awslabs/amazon-ecr-credential-helper/issues/84
> vendor: update aws-sdk-go

- Makefile
> Fixes awslabs/amazon-ecr-credential-helper#108

- README.md
This sequence of numbers is off by one.
> typo - sequential numeral

- doc/docker-credential-ecr-login.1
> man: add manual page

- ecr-login/Gopkg.lock
dep was complaining, this fixed its complaint
/cc @SoManyHs 
> dep: update Gopkg.lock

- amazon-ecr-credential-helper.spec
Add aarch64 to the spec file
/cc @jahkeup; I'll need your help testing the build of this
> spec: add aarch64 support

- docs/docker-credential-ecr-login.1
> docs: fix spelling error in manual page

- README.md
- docs/packaging.md
docs: add Debian and Ubuntu packaging and install
> docs: add Debian and Ubuntu packaging and install

- ecr-login/api/client.go
- ecr-login/cache/credentials.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- debian/packaging-debian.md
Packaging instructions for Debian
> debian: packaging instructions

- debian/changelog
- debian/rules
Addresses https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930104.
> Ensure that DEB_HOST_GNU_TYPE is initialized in debian/rules

- Makefile
> makefile: add arm64/aarch64 build

- README.md
https://github.com/awslabs/amazon-ecr-credential-helper/issues/164
Added additional instructions to the readme.
cc @sipsma
> readme: add AWS_PROFILE and AWS_SDK_LOAD_CONFIG

- .travis.yml
- Dockerfile
- README.md
> Update Go version

- README.md
Update the Repology badges in the README
> readme: update Repology badges

- debian/Dockerfile
- debian/changelog
* Update debian/Dockerfile with the explicit dependency on golang-github-stretchr-testify-dev
* Finalize debian/changelog
cc @tianon
> debian: updates for 0.3.1-2

- .github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
> Add GitHub's CODEOWNERS file

- .github/workflows/build.yaml
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
Update actions runner OS images.
Update actions/checkout and actions/setup-go packages.
> Update GitHub actions CI workflow

- .github/workflows/codeql.yml
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
Add CodeQL security scanning workflow to run on each PR and once a week.
> Add CodeQL security scanning workflow

- .github/workflows/auto-merge.yml
N/A
Add auto-merge of dependabot pull-requests.
> Add dependabot auto-merge

- amazon-ecr-credential-helper.spec
Update build version and add changelog for AL rpms
> Update AL build version and add changelog

- amazon-ecr-credential-helper.spec
Hi, I'm from the Amazon Linux team and we would like to rebuild this package with the most recent golang in our package repositories (1.20.7). To do this the package build number must be incremented. Thanks!
> Increment build number

- ecr-login/cache/file.go
> chore: remove refs to deprecated io/ioutil

- .github/dependabot.yml
N/A
Adds dependabot updates for GitHub Actions packages.
> Add dependabot updates for GitHub Actions packages

- README.md
Closes #791
This change adds a disclaimer to the project's README regarding support for Windows ARM binaries.
> Add disclaimer for Windows ARM support as experimental

- amazon-ecr-credential-helper.spec
> Rebuild with golang-1.22.3

- README.md
#370 (sorta)
- Add install information for Alpine Linux aports
> Add install information for Alpine Linux aports

- amazon-ecr-credential-helper.spec
*Issue #, if available:* N/A
Correct error in changelog entry which appears to be blocking RPM build.
> Correct date in changelog

- README.md
Update the README.md table of contensts to include a reference to the Windows section.
> Add Windows to README table of contents

- README.md
> docs: Add note on using credHelpers for multi-registry authentication

- README.md
Related to issues: #916 #81
Expand on where the configuration settings should reside. Distinguish between the user and root/system contexts and the corresponding directories for configurations files.
> docs: Add details to configuration section for Windows.

- ecr-login/api/client.go
- ecr-login/api/client_test.go
#967 
Update regex validation for dualstack ECR endpoints
> Update regex validation for dualstack ECR endpoints

- amazon-ecr-credential-helper.spec
Update amazonlinux spec file version and add changelogs
> chore: update to v0.10.0

- amazon-ecr-credential-helper.spec
> fix: date format in spec file

- amazon-ecr-credential-helper.spec
> update spec file version to 0.10.1
